### PR TITLE
Product & Order Test

### PR DESCRIPTION
**Pull request by xembatman**
Added Test cases and stuff

(please tell me if something is wrong)

### CODE REVIEW

**Comment by xembatman** [comment]
ha valami rossz please tell me & what can I still do for the project ^^

**Comment by Lovasz-Akos** [comment]
stop closing it omg

**Review by Lovasz-Akos — APPROVED** [review]
Accepting with changes I made

**Comment by Lovasz-Akos** [comment]
(but commit messages are not helpful)

**Pull request merged**
